Creating sign in pages
solaris-senior-design/solaris-mobile-app pull request #12
Opened 2022-10-06 21:44 UTC by jaimegarjr

2022-11-04 19:48 UTC, Oziel-Sal requested changes
Everything looks great. You left some commented code in some of your files.

2022-11-04 19:48 UTC, Oziel-Sal commented on lib/widgets/metric_card_section.dart
> +    ); // 'https://solaris-web-server.herokuapp.com'
Remove comment

2022-11-04 19:48 UTC, Oziel-Sal commented on lib/widgets/metric_line_chart_section.dart
> +    // Map<String, dynamic> lineChartData =
remove comments

2022-11-04 19:48 UTC, Oziel-Sal commented on lib/widgets/power_bar_chart_section.dart
> +    // Map<String, dynamic> barChartData = await NetworkHelper.getData(
comments

2022-11-05 02:36 UTC, jaimegarjr commented on lib/widgets/power_bar_chart_section.dart
> +    // Map<String, dynamic> barChartData = await NetworkHelper.getData(
needed before we set up 7 days of data

2022-11-05 03:43 UTC, Oziel-Sal approved these changes
LGTM

2022-11-05 13:48 UTC, merged